"""Parallel Case Executor for Test Cases.

This module provides parallel execution of test cases generated by the planner,
managing a waiting list, execution list, and completed list with configurable
concurrency control.
"""

import asyncio
import logging
from typing import Any, Dict, List, Optional
from datetime import datetime

from webqa_agent.browser.session_pool import BrowserSessionPool
from webqa_agent.testers.case_gen.single_case_runner import execute_single_case_standalone


class ParallelCaseExecutor:
    """Manages parallel execution of test cases with session pooling.

    Architecture:
    - Waiting List: Cases pending execution
    - Execution List: Cases currently running (max = max_concurrent_cases)
    - Completed List: Finished cases with results

    Features:
    - Concurrent case execution with configurable limit
    - Browser session pool management
    - Error isolation (case failures don't affect others)
    - Real-time progress tracking
    """

    def __init__(
        self,
        llm_config: Dict[str, Any],
        max_concurrent_cases: int = 2,
        session_pool_size: Optional[int] = None,
        browser_config: Optional[Dict] = None
    ):
        """Initialize the parallel case executor.

        Args:
            llm_config: LLM configuration dict
            max_concurrent_cases: Maximum number of cases to execute concurrently
            session_pool_size: Browser session pool size (defaults to max_concurrent_cases)
            browser_config: Browser configuration dict
        """
        self.llm_config = llm_config
        self.max_concurrent_cases = max_concurrent_cases
        self.session_pool_size = session_pool_size or max_concurrent_cases
        self.browser_config = browser_config or {}

        # Execution state
        self.waiting_list: List[Dict[str, Any]] = []
        self.execution_list: List[Dict[str, Any]] = []
        self.completed_list: List[Dict[str, Any]] = []

        # Session pool
        self.session_pool: Optional[BrowserSessionPool] = None
        self._owns_session_pool: bool = True  # Track if we created the pool

        # Concurrency control
        self._semaphore: Optional[asyncio.Semaphore] = None
        self._tasks: List[asyncio.Task] = []

        # Statistics
        self.stats = {
            'total_cases': 0,
            'completed': 0,
            'failed': 0,
            'passed': 0,
            'warning': 0,
            'start_time': None,
            'end_time': None
        }

        logging.info(
            f"ParallelCaseExecutor initialized: "
            f"max_concurrent_cases={max_concurrent_cases}, "
            f"session_pool_size={self.session_pool_size}"
        )

    async def execute_cases_parallel(
        self,
        cases: List[Dict[str, Any]],
        url: str,
        cookies: Optional[list] = None,
        dynamic_step_generation: Optional[Dict] = None,
        language: str = 'en-US',
        skip_pool_initialization: bool = False
    ) -> Dict[str, Any]:
        """Execute test cases in parallel with session pooling.

        Args:
            cases: List of test case dicts from planner
            url: Target URL
            cookies: Optional cookies for sessions
            dynamic_step_generation: Optional dynamic step generation config
            language: UI language ('en-US' or 'zh-CN')

        Returns:
            Dict with aggregated results:
            {
                'case_results': List[dict],  # All case_result dicts
                'recorded_cases': List[dict],  # All recorded_case dicts
                'modified_cases': List[dict],  # Cases with dynamic steps
                'stats': dict,  # Execution statistics
                'completed_list': List[dict]  # Full result objects
            }
        """
        if not cases:
            logging.warning("No cases to execute")
            return self._empty_results()

        self.stats['total_cases'] = len(cases)
        self.stats['start_time'] = datetime.now().isoformat()

        # Initialize waiting list
        self.waiting_list = list(cases)  # Copy list
        self.execution_list = []
        self.completed_list = []

        logging.info(f"Starting parallel execution of {len(cases)} cases")
        logging.info(f"Waiting List: {len(self.waiting_list)} cases")

        try:
            # Initialize session pool (unless already provided)
            if not skip_pool_initialization:
                await self._initialize_session_pool()
                self._owns_session_pool = True
            else:
                logging.info("[ParallelCaseExecutor] Using existing session pool (skip_pool_initialization=True)")
                if not self.session_pool:
                    raise RuntimeError("skip_pool_initialization=True but no session_pool provided")
                self._owns_session_pool = False  # Don't close external pool

            # Initialize semaphore for concurrency control
            self._semaphore = asyncio.Semaphore(self.max_concurrent_cases)

            # Create tasks for all cases
            tasks = []
            for case in cases:
                task = asyncio.create_task(
                    self._execute_case_with_control(
                        case=case,
                        url=url,
                        cookies=cookies,
                        dynamic_step_generation=dynamic_step_generation,
                        language=language
                    )
                )
                tasks.append(task)
                self._tasks.append(task)

            # Wait for all tasks to complete
            results = await asyncio.gather(*tasks, return_exceptions=True)

            # Process results
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    logging.error(f"Case {i} raised exception: {result}", exc_info=result)
                    # Create error result
                    error_result = {
                        'case_result': {
                            'case_name': cases[i].get('name', f'Case {i}'),
                            'status': 'failed',
                            'final_summary': f'Exception: {str(result)}',
                            'failure_type': 'critical'
                        },
                        'recorded_case': None,
                        'modified_case': None
                    }
                    self.completed_list.append(error_result)
                    self.stats['failed'] += 1

            self.stats['end_time'] = datetime.now().isoformat()
            self.stats['completed'] = len(self.completed_list)

            logging.info(f"Parallel execution completed: {self.stats['completed']}/{self.stats['total_cases']} cases")
            logging.info(f"Results: Passed={self.stats['passed']}, Failed={self.stats['failed']}, Warning={self.stats['warning']}")

            return self._aggregate_results()

        except Exception as e:
            logging.error(f"Parallel execution failed: {e}", exc_info=True)
            raise

        finally:
            # Clean up session pool
            await self._cleanup_session_pool()

    async def _execute_case_with_control(
        self,
        case: Dict[str, Any],
        url: str,
        cookies: Optional[list],
        dynamic_step_generation: Optional[Dict],
        language: str
    ) -> Dict[str, Any]:
        """Execute a single case with concurrency control.

        This method:
        1. Waits for semaphore slot (enforces max_concurrent_cases)
        2. Moves case from waiting_list to execution_list
        3. Acquires session from pool
        4. Executes case via single_case_runner
        5. Releases session back to pool
        6. Moves case from execution_list to completed_list
        7. Releases semaphore slot

        Args:
            case: Test case dict
            url: Target URL
            cookies: Optional cookies
            dynamic_step_generation: Optional dynamic step config
            language: UI language

        Returns:
            Dict with execution results
        """
        case_name = case.get('name', 'Unnamed Case')

        # Wait for semaphore slot
        async with self._semaphore:
            # Move from waiting to execution
            if case in self.waiting_list:
                self.waiting_list.remove(case)
            self.execution_list.append(case)

            logging.info(
                f"[ParallelCaseExecutor] Starting case: {case_name} "
                f"(Waiting: {len(self.waiting_list)}, Executing: {len(self.execution_list)}, "
                f"Completed: {len(self.completed_list)})"
            )

            session = None
            try:
                # Acquire session from pool
                session = await self.session_pool.acquire(timeout=60.0)
                logging.debug(f"[ParallelCaseExecutor] Acquired session {session.session_id} for case: {case_name}")

                # Execute case
                result = await execute_single_case_standalone(
                    case=case,
                    session=session,
                    llm_config=self.llm_config,
                    url=url,
                    cookies=cookies,
                    dynamic_step_generation=dynamic_step_generation,
                    language=language
                )

                # Update statistics
                case_result = result.get('case_result', {})
                status = case_result.get('status', 'unknown').lower()

                if status == 'passed':
                    self.stats['passed'] += 1
                elif status == 'failed':
                    self.stats['failed'] += 1
                elif status == 'warning':
                    self.stats['warning'] += 1

                logging.info(f"[ParallelCaseExecutor] Completed case: {case_name} (status: {status})")

                return result

            except Exception as e:
                logging.error(f"[ParallelCaseExecutor] Error executing case '{case_name}': {e}", exc_info=True)

                # Create error result
                error_result = {
                    'case_result': {
                        'case_name': case_name,
                        'status': 'failed',
                        'final_summary': f'Execution error: {str(e)}',
                        'failure_type': 'critical'
                    },
                    'recorded_case': None,
                    'modified_case': None,
                    'error': str(e)
                }

                self.stats['failed'] += 1
                return error_result

            finally:
                # Release session back to pool
                if session:
                    await self.session_pool.release(session)
                    logging.debug(f"[ParallelCaseExecutor] Released session {session.session_id}")

                # Move from execution to completed
                if case in self.execution_list:
                    self.execution_list.remove(case)

                # Add result to completed list
                # Note: result is added in gather() to maintain order
                self.completed_list.append(result if 'result' in locals() else error_result)

                logging.debug(
                    f"[ParallelCaseExecutor] Case '{case_name}' moved to completed list "
                    f"(Waiting: {len(self.waiting_list)}, Executing: {len(self.execution_list)}, "
                    f"Completed: {len(self.completed_list)})"
                )

    async def _initialize_session_pool(self):
        """Initialize the browser session pool."""
        logging.info(f"Initializing session pool with size={self.session_pool_size}")

        self.session_pool = BrowserSessionPool(
            pool_size=self.session_pool_size,
            browser_config=self.browser_config
        )

        await self.session_pool.initialize()

        pool_stats = self.session_pool.get_pool_stats()
        logging.info(f"Session pool initialized: {pool_stats}")

    async def _cleanup_session_pool(self):
        """Clean up the browser session pool."""
        if self.session_pool and self._owns_session_pool:
            logging.info("Closing session pool (owned by executor)...")
            await self.session_pool.close_all()
            logging.info("Session pool closed")
        elif self.session_pool and not self._owns_session_pool:
            logging.info("Skipping session pool cleanup (external pool, not owned by executor)")

    def _aggregate_results(self) -> Dict[str, Any]:
        """Aggregate results from completed list.

        Returns:
            Dict with aggregated results
        """
        case_results = []
        recorded_cases = []
        modified_cases = []

        for result in self.completed_list:
            if not result:
                continue

            case_result = result.get('case_result')
            recorded_case = result.get('recorded_case')
            modified_case = result.get('modified_case')

            if case_result:
                case_results.append(case_result)

            if recorded_case:
                recorded_cases.append(recorded_case)

            if modified_case:
                modified_cases.append(modified_case)

        return {
            'case_results': case_results,
            'recorded_cases': recorded_cases,
            'modified_cases': modified_cases,
            'stats': dict(self.stats),
            'completed_list': self.completed_list
        }

    def _empty_results(self) -> Dict[str, Any]:
        """Return empty results structure."""
        return {
            'case_results': [],
            'recorded_cases': [],
            'modified_cases': [],
            'stats': dict(self.stats),
            'completed_list': []
        }

    def get_execution_status(self) -> Dict[str, Any]:
        """Get current execution status.

        Returns:
            Dict with status information
        """
        return {
            'waiting_count': len(self.waiting_list),
            'executing_count': len(self.execution_list),
            'completed_count': len(self.completed_list),
            'total_cases': self.stats['total_cases'],
            'stats': dict(self.stats),
            'waiting_cases': [c.get('name', 'Unnamed') for c in self.waiting_list],
            'executing_cases': [c.get('name', 'Unnamed') for c in self.execution_list],
            'completed_cases': [c.get('name', 'Unnamed') for c in self.completed_list]
        }

    async def cancel_all(self):
        """Cancel all running tasks (emergency stop)."""
        logging.warning("Cancelling all running tasks...")

        for task in self._tasks:
            if not task.done():
                task.cancel()

        # Wait for tasks to finish cancelling
        await asyncio.gather(*self._tasks, return_exceptions=True)

        logging.info("All tasks cancelled")

        # Clean up session pool
        await self._cleanup_session_pool()
