"""Parallel Case Executor for Test Cases.

This module provides parallel execution of test cases generated by the planner,
managing a waiting list, execution list, and completed list with configurable
concurrency control.

Key Feature: Parallel Reflection (No Lock Required)
- Each case has its own browser session
- Reflection uses the case's session independently
- New cases are queued via thread-safe asyncio.Queue
- FINISH signal via thread-safe asyncio.Event
"""

import asyncio
import logging
from typing import Any, Dict, List, Optional
from datetime import datetime

from webqa_agent.browser.session_pool import BrowserSessionPool
from webqa_agent.testers.case_gen.single_case_runner import execute_single_case_standalone
from webqa_agent.executor.case_result_saver import CaseResultSaver
from webqa_agent.executor.case_reflector import CaseReflector


class ParallelCaseExecutor:
    """Manages parallel execution of test cases with session pooling.

    Architecture:
    - Waiting List: Cases pending execution
    - Execution List: Cases currently running (max = max_concurrent_cases)
    - Completed List: Finished cases with results

    Features:
    - Concurrent case execution with configurable limit
    - Browser session pool management
    - Error isolation (case failures don't affect others)
    - Real-time progress tracking
    """

    def __init__(
        self,
        llm_config: Dict[str, Any],
        max_concurrent_cases: int = 2,
        session_pool_size: Optional[int] = None,
        browser_config: Optional[Dict] = None,
        case_result_saver: Optional[CaseResultSaver] = None,
        test_id: Optional[str] = None,
        test_name: Optional[str] = None
    ):
        """Initialize the parallel case executor.

        Args:
            llm_config: LLM configuration dict
            max_concurrent_cases: Maximum number of cases to execute concurrently
            session_pool_size: Browser session pool size (defaults to max_concurrent_cases)
            browser_config: Browser configuration dict
            case_result_saver: Optional CaseResultSaver for saving case results
            test_id: Test ID (for case result saving)
            test_name: Test name (for case result saving)
        """
        self.llm_config = llm_config
        self.max_concurrent_cases = max_concurrent_cases
        self.session_pool_size = session_pool_size or max_concurrent_cases
        self.browser_config = browser_config or {}
        self.case_result_saver = case_result_saver
        self.test_id = test_id
        self.test_name = test_name

        # Execution state
        self.waiting_list: List[Dict[str, Any]] = []
        self.execution_list: List[Dict[str, Any]] = []
        self.completed_list: List[Dict[str, Any]] = []

        # Session pool
        self.session_pool: Optional[BrowserSessionPool] = None
        self._owns_session_pool: bool = True  # Track if we created the pool

        # Task tracking
        self._tasks: List[asyncio.Task] = []
        self._reflection_tasks: List[asyncio.Task] = []  # Track async reflection tasks

        # Statistics
        self.stats = {
            'total_cases': 0,
            'completed': 0,
            'failed': 0,
            'passed': 0,
            'warning': 0,
            'start_time': None,
            'end_time': None
        }

        # Case counter for incremental saves
        self._case_counter = 0

        logging.info(
            f"ParallelCaseExecutor initialized: "
            f"max_concurrent_cases={max_concurrent_cases}, "
            f"session_pool_size={self.session_pool_size}, "
            f"case_result_saver={'enabled' if case_result_saver else 'disabled'}"
        )

    async def execute_cases_parallel(
        self,
        cases: List[Dict[str, Any]],
        url: str,
        cookies: Optional[list] = None,
        dynamic_step_generation: Optional[Dict] = None,
        language: str = 'en-US',
        skip_pool_initialization: bool = False
    ) -> Dict[str, Any]:
        """Execute test cases in parallel with session pooling.

        Args:
            cases: List of test case dicts from planner
            url: Target URL
            cookies: Optional cookies for sessions
            dynamic_step_generation: Optional dynamic step generation config
            language: UI language ('en-US' or 'zh-CN')

        Returns:
            Dict with aggregated results:
            {
                'case_results': List[dict],  # All case_result dicts
                'recorded_cases': List[dict],  # All recorded_case dicts
                'modified_cases': List[dict],  # Cases with dynamic steps
                'stats': dict,  # Execution statistics
                'completed_list': List[dict]  # Full result objects
            }
        """
        if not cases:
            logging.warning("No cases to execute")
            return self._empty_results()

        self.stats['total_cases'] = len(cases)
        self.stats['start_time'] = datetime.now().isoformat()

        # Initialize waiting list with original indices
        # Add original index to each case (1-based to match cases.json position)
        for i, case in enumerate(cases, start=1):
            case['_original_index'] = i

        self.waiting_list = list(cases)  # Copy list
        self.execution_list = []
        self.completed_list = []

        logging.info(f"Starting parallel execution of {len(cases)} cases")
        logging.info(f"Waiting List: {len(self.waiting_list)} cases")

        try:
            # Initialize session pool (unless already provided)
            if not skip_pool_initialization:
                await self._initialize_session_pool()
                self._owns_session_pool = True
            else:
                logging.info("[ParallelCaseExecutor] Using existing session pool (skip_pool_initialization=True)")
                if not self.session_pool:
                    raise RuntimeError("skip_pool_initialization=True but no session_pool provided")
                self._owns_session_pool = False  # Don't close external pool

            # Create tasks for all cases (Queue controls concurrency)
            tasks = []
            for case in cases:
                task = asyncio.create_task(
                    self._execute_case_with_control(
                        case=case,
                        url=url,
                        cookies=cookies,
                        dynamic_step_generation=dynamic_step_generation,
                        language=language
                    )
                )
                tasks.append(task)
                self._tasks.append(task)

            # Wait for all tasks to complete
            results = await asyncio.gather(*tasks, return_exceptions=True)

            # Process results
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    logging.error(f"Case {i} raised exception: {result}", exc_info=result)
                    # Create error result
                    error_result = {
                        'case_result': {
                            'case_name': cases[i].get('name', f'Case {i}'),
                            'status': 'failed',
                            'final_summary': f'Exception: {str(result)}',
                            'failure_type': 'critical'
                        },
                        'recorded_case': None,
                        'modified_case': None
                    }
                    self.completed_list.append(error_result)
                    self.stats['failed'] += 1

            self.stats['end_time'] = datetime.now().isoformat()
            self.stats['completed'] = len(self.completed_list)

            logging.info(f"Parallel execution completed: {self.stats['completed']}/{self.stats['total_cases']} cases")
            logging.info(f"Results: Passed={self.stats['passed']}, Failed={self.stats['failed']}, Warning={self.stats['warning']}")

            return self._aggregate_results()

        except Exception as e:
            logging.error(f"Parallel execution failed: {e}", exc_info=True)
            raise

        finally:
            # Clean up session pool
            await self._cleanup_session_pool()

    async def _execute_case_with_control(
        self,
        case: Dict[str, Any],
        url: str,
        cookies: Optional[list],
        dynamic_step_generation: Optional[Dict],
        language: str
    ) -> Dict[str, Any]:
        """Execute a single case with Queue-based concurrency control.

        This method:
        1. Acquires session from pool (Queue blocks when empty - this IS concurrency control)
        2. Moves case from waiting_list to execution_list
        3. Executes case via single_case_runner
        4. Releases session back to pool
        5. Moves case from execution_list to completed_list

        Args:
            case: Test case dict
            url: Target URL
            cookies: Optional cookies
            dynamic_step_generation: Optional dynamic step config
            language: UI language

        Returns:
            Dict with execution results
        """
        case_name = case.get('name', 'Unnamed Case')

        session = None
        result = None

        try:
            # Queue.get() blocks when empty - this IS the concurrency control
            # Use None timeout to wait indefinitely - Queue naturally limits concurrency
            session = await self.session_pool.acquire(timeout=None)

            # Move from waiting to execution (after acquiring session)
            if case in self.waiting_list:
                self.waiting_list.remove(case)
            self.execution_list.append(case)

            logging.info(
                f"[ParallelCaseExecutor] Starting case: {case_name} "
                f"(Waiting: {len(self.waiting_list)}, Executing: {len(self.execution_list)}, "
                f"Completed: {len(self.completed_list)})"
            )
            logging.debug(f"[ParallelCaseExecutor] Acquired session {session.session_id} for case: {case_name}")

            # Execute case
            result = await execute_single_case_standalone(
                case=case,
                session=session,
                llm_config=self.llm_config,
                url=url,
                cookies=cookies,
                dynamic_step_generation=dynamic_step_generation,
                language=language
            )

            # Update statistics
            case_result = result.get('case_result', {})
            status = case_result.get('status', 'unknown').lower()

            if status == 'passed':
                self.stats['passed'] += 1
            elif status == 'failed':
                self.stats['failed'] += 1
            elif status == 'warning':
                self.stats['warning'] += 1

            logging.info(f"[ParallelCaseExecutor] Completed case: {case_name} (status: {status})")

            # Incremental save
            await self._save_case_result_incrementally(
                case_result,
                case_name,
                case_index=case.get('_original_index'),
                recorded_case=result.get('recorded_case')
            )

            return result

        except asyncio.CancelledError:
            logging.warning(f"[ParallelCaseExecutor] Case '{case_name}' was cancelled")
            if result is None:
                result = {
                    'case_result': {
                        'case_name': case_name,
                        'status': 'cancelled',
                        'final_summary': 'Case execution was interrupted',
                        'failure_type': 'interrupted'
                    },
                    'recorded_case': None,
                    'modified_case': None,
                    'error': 'Test was cancelled'
                }
            self.stats['failed'] += 1
            await self._save_case_result_incrementally(
                result.get('case_result', {}),
                case_name,
                case_index=case.get('_original_index'),
                recorded_case=result.get('recorded_case')
            )
            raise

        except Exception as e:
            logging.error(f"[ParallelCaseExecutor] Error executing case '{case_name}': {e}", exc_info=True)
            if result is None:
                result = {
                    'case_result': {
                        'case_name': case_name,
                        'status': 'failed',
                        'final_summary': f'Execution error: {str(e)}',
                        'failure_type': 'critical'
                    },
                    'recorded_case': None,
                    'modified_case': None,
                    'error': str(e)
                }
            self.stats['failed'] += 1
            await self._save_case_result_incrementally(
                result.get('case_result', {}),
                case_name,
                case_index=case.get('_original_index'),
                recorded_case=result.get('recorded_case')
            )
            return result

        finally:
            if session:
                await self.session_pool.release(session)
                logging.debug(f"[ParallelCaseExecutor] Released session {session.session_id}")
            if case in self.execution_list:
                self.execution_list.remove(case)
            if result is not None:
                self.completed_list.append(result)
            logging.debug(
                f"[ParallelCaseExecutor] Case '{case_name}' done "
                f"(Waiting: {len(self.waiting_list)}, Executing: {len(self.execution_list)}, "
                f"Completed: {len(self.completed_list)})"
            )

    async def _initialize_session_pool(self):
        """Initialize the browser session pool."""
        logging.info(f"Initializing session pool with size={self.session_pool_size}")

        self.session_pool = BrowserSessionPool(
            pool_size=self.session_pool_size,
            browser_config=self.browser_config
        )

        await self.session_pool.initialize()

        pool_stats = self.session_pool.get_pool_stats()
        logging.info(f"Session pool initialized: {pool_stats}")

    async def _cleanup_session_pool(self):
        """Clean up the browser session pool."""
        if self.session_pool and self._owns_session_pool:
            logging.info("Closing session pool (owned by executor)...")
            await self.session_pool.close_all()
            logging.info("Session pool closed")
        elif self.session_pool and not self._owns_session_pool:
            logging.info("Skipping session pool cleanup (external pool, not owned by executor)")

    def _aggregate_results(self) -> Dict[str, Any]:
        """Aggregate results from completed list.

        Returns:
            Dict with aggregated results
        """
        case_results = []
        recorded_cases = []
        modified_cases = []

        for result in self.completed_list:
            if not result:
                continue

            case_result = result.get('case_result')
            recorded_case = result.get('recorded_case')
            modified_case = result.get('modified_case')

            if case_result:
                case_results.append(case_result)

            if recorded_case:
                recorded_cases.append(recorded_case)

            if modified_case:
                modified_cases.append(modified_case)

        return {
            'case_results': case_results,
            'recorded_cases': recorded_cases,
            'modified_cases': modified_cases,
            'stats': dict(self.stats),
            'completed_list': self.completed_list
        }

    def _empty_results(self) -> Dict[str, Any]:
        """Return empty results structure."""
        return {
            'case_results': [],
            'recorded_cases': [],
            'modified_cases': [],
            'stats': dict(self.stats),
            'completed_list': []
        }

    def get_execution_status(self) -> Dict[str, Any]:
        """Get current execution status.

        Returns:
            Dict with status information
        """
        return {
            'waiting_count': len(self.waiting_list),
            'executing_count': len(self.execution_list),
            'completed_count': len(self.completed_list),
            'total_cases': self.stats['total_cases'],
            'stats': dict(self.stats),
            'waiting_cases': [c.get('name', 'Unnamed') for c in self.waiting_list],
            'executing_cases': [c.get('name', 'Unnamed') for c in self.execution_list],
            'completed_cases': [c.get('name', 'Unnamed') for c in self.completed_list]
        }

    async def cancel_all(self):
        """Cancel all running tasks (emergency stop)."""
        logging.warning("Cancelling all running tasks...")

        for task in self._tasks:
            if not task.done():
                task.cancel()

        # Wait for tasks to finish cancelling
        await asyncio.gather(*self._tasks, return_exceptions=True)

        logging.info("All tasks cancelled")

        # Clean up session pool
        await self._cleanup_session_pool()

    async def _save_case_result_incrementally(
        self,
        case_result: Dict[str, Any],
        case_name: str,
        case_index: Optional[int] = None,
        recorded_case: Optional[Dict] = None
    ):
        """Save individual case result incrementally.

        Args:
            case_result: Case result dictionary
            case_name: Case name
            case_index: Original case index from cases.json (1-based), if available
            recorded_case: Recorded case data with full step details
        """
        if not self.case_result_saver or not self.test_id:
            # Incremental saving not enabled
            return

        try:
            # Use original case index if provided, otherwise use counter
            if case_index is not None:
                case_number = case_index
            else:
                self._case_counter += 1
                case_number = self._case_counter

            # Extract simplified steps from recorded_case (without screenshots)
            simplified_steps = self._extract_simplified_steps(recorded_case)

            # Build case result file data
            case_data = {
                "test_name": self.test_name or "Unknown Test",
                "case_name": case_name,
                "case_number": case_number,
                "case_result": case_result,
                "steps": simplified_steps  # Add step details
            }

            # Generate filename using case_number only (case_01.json, case_02.json, etc.)
            filename = f"case_{case_number:02d}.json"
            filepath = self.case_result_saver.case_results_dir / filename
            temp_filepath = self.case_result_saver.case_results_dir / f".{filename}.tmp"

            # Atomic write
            await self.case_result_saver._write_json_atomic(
                temp_filepath,
                filepath,
                case_data
            )

            # Update manifest with case metadata
            await self.case_result_saver.save_case_result(
                case_number=case_number,
                case_name=case_name,
                status=case_result.get('status', 'unknown')
            )

            logging.info(
                f"[ParallelCaseExecutor] Incremental save: "
                f"{case_name} (status: {case_result.get('status', 'unknown')}) -> {filename}"
            )

        except Exception as e:
            logging.error(
                f"[ParallelCaseExecutor] Failed to save case result incrementally "
                f"(case: {case_name}): {e}",
                exc_info=True
            )
            # Non-fatal: execution continues

    def _extract_simplified_steps(self, recorded_case: Optional[Dict]) -> List[Dict]:
        """Extract simplified step information from recorded_case.

        Args:
            recorded_case: Full recorded case data with screenshots

        Returns:
            List of simplified step dicts with description and status only
        """
        if not recorded_case or not isinstance(recorded_case, dict):
            return []

        steps = recorded_case.get('steps', [])
        if not isinstance(steps, list):
            return []

        # Use list comprehension for better performance
        return [
            {
                "description": step.get('description', ''),
                "status": step.get('status', 'unknown')
            }
            for step in steps
            if isinstance(step, dict)
        ]

    # =========================================================================
    # Parallel Execution with Reflection (No Lock Required)
    # =========================================================================

    async def execute_cases_with_reflection(
        self,
        cases: List[Dict[str, Any]],
        url: str,
        llm_client,  # LLM client for reflection
        cookies: Optional[list] = None,
        dynamic_step_generation: Optional[Dict] = None,
        language: str = 'en-US',
        business_objectives: str = "",
        reflection_config: Optional[Dict] = None,
        skip_pool_initialization: bool = False
    ) -> Dict[str, Any]:
        """Execute test cases in parallel with independent reflection after each case.

        Key Design: No Lock Required
        - Each case has its own browser session
        - Reflection uses the case's session (independent)
        - New cases queued via asyncio.Queue (thread-safe)
        - FINISH signal via asyncio.Event (thread-safe)

        Architecture:
            Case1(Session1) ──→ execute ──→ reflect ──→ Queue.put(new_cases)
            Case2(Session2) ──→ execute ──→ reflect ──→ Queue.put(new_cases)
            Case3(Session3) ──→ execute ──→ reflect ──→ Queue.put(new_cases)
                                                              ↓
                                                    asyncio.Queue (thread-safe)
                                                              ↓
                                                    NewCaseConsumer ──→ execute

        Args:
            cases: List of test case dicts from planner
            url: Target URL
            llm_client: LLM client for reflection API calls
            cookies: Optional cookies for sessions
            dynamic_step_generation: Optional dynamic step generation config
            language: UI language ('en-US' or 'zh-CN')
            business_objectives: Business objectives for reflection context
            reflection_config: Optional reflection configuration:
                - enabled: bool (default: True)
                - reflect_on_failure_only: bool (default: False)
                - max_new_cases_per_reflect: int (default: 3)
            skip_pool_initialization: Skip session pool init if already provided

        Returns:
            Dict with aggregated results including reflection stats
        """
        if not cases:
            logging.warning("No cases to execute")
            return self._empty_results_with_reflection()

        self.stats['total_cases'] = len(cases)
        self.stats['start_time'] = datetime.now().isoformat()

        # Initialize waiting list with original indices
        for i, case in enumerate(cases, start=1):
            case['_original_index'] = i

        self.waiting_list = list(cases)
        self.execution_list = []
        self.completed_list = []

        # Reset reflection tasks for this execution
        self._reflection_tasks = []

        # Reflection infrastructure (thread-safe, no lock needed)
        new_cases_queue: asyncio.Queue = asyncio.Queue()
        finish_event: asyncio.Event = asyncio.Event()

        # Create reflector
        reflector = CaseReflector(
            new_cases_queue=new_cases_queue,
            finish_event=finish_event,
            llm_client=llm_client,
            business_objectives=business_objectives,
            language=language,
            reflection_config=reflection_config
        )

        # Track dynamically added cases
        dynamic_case_counter = len(cases)

        logging.info(f"Starting parallel execution with reflection: {len(cases)} cases")
        logging.info(f"Reflection config: {reflection_config or 'default'}")

        try:
            # Initialize session pool
            if not skip_pool_initialization:
                await self._initialize_session_pool()
                self._owns_session_pool = True
            else:
                if not self.session_pool:
                    raise RuntimeError("skip_pool_initialization=True but no session_pool provided")
                self._owns_session_pool = False

            # Start new case consumer task (Queue controls concurrency)
            consumer_task = asyncio.create_task(
                self._new_case_consumer(
                    new_cases_queue=new_cases_queue,
                    finish_event=finish_event,
                    url=url,
                    cookies=cookies,
                    dynamic_step_generation=dynamic_step_generation,
                    language=language,
                    reflector=reflector,
                    dynamic_case_counter_start=dynamic_case_counter
                )
            )

            # Create tasks for initial cases
            tasks = []
            for case in cases:
                task = asyncio.create_task(
                    self._execute_case_with_reflection(
                        case=case,
                        url=url,
                        cookies=cookies,
                        dynamic_step_generation=dynamic_step_generation,
                        language=language,
                        reflector=reflector,
                        finish_event=finish_event
                    )
                )
                tasks.append(task)
                self._tasks.append(task)

            # Wait for initial tasks
            results = await asyncio.gather(*tasks, return_exceptions=True)

            # Process initial results
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    logging.error(f"Case {i} raised exception: {result}", exc_info=result)
                    error_result = {
                        'case_result': {
                            'case_name': cases[i].get('name', f'Case {i}'),
                            'status': 'failed',
                            'final_summary': f'Exception: {str(result)}',
                            'failure_type': 'critical'
                        },
                        'recorded_case': None,
                        'modified_case': None
                    }
                    self.completed_list.append(error_result)
                    self.stats['failed'] += 1

            # Signal consumer to stop and wait for it
            finish_event.set()
            try:
                await asyncio.wait_for(consumer_task, timeout=5.0)
            except asyncio.TimeoutError:
                logging.warning("Consumer task timeout, cancelling...")
                consumer_task.cancel()
                try:
                    await consumer_task
                except asyncio.CancelledError:
                    pass

            # Wait for all async reflection tasks to complete
            if self._reflection_tasks:
                logging.info(f"[Reflection] Waiting for {len(self._reflection_tasks)} reflection tasks to complete...")
                reflection_results = await asyncio.gather(*self._reflection_tasks, return_exceptions=True)
                # Log any failed reflection tasks
                for i, result in enumerate(reflection_results):
                    if isinstance(result, Exception):
                        logging.error(f"[Reflection] Task {i} failed: {result}")
                logging.info("[Reflection] All reflection tasks completed")

            self.stats['end_time'] = datetime.now().isoformat()
            self.stats['completed'] = len(self.completed_list)

            logging.info(
                f"Parallel execution with reflection completed: "
                f"{self.stats['completed']}/{self.stats['total_cases']} cases"
            )
            logging.info(
                f"Results: Passed={self.stats['passed']}, "
                f"Failed={self.stats['failed']}, Warning={self.stats['warning']}"
            )
            logging.info(f"Reflection stats: {reflector.get_stats()}")

            return self._aggregate_results_with_reflection(reflector.get_stats())

        except Exception as e:
            logging.error(f"Parallel execution with reflection failed: {e}", exc_info=True)
            raise

        finally:
            await self._cleanup_session_pool()

    async def _execute_case_with_reflection(
        self,
        case: Dict[str, Any],
        url: str,
        cookies: Optional[list],
        dynamic_step_generation: Optional[Dict],
        language: str,
        reflector: CaseReflector,
        finish_event: asyncio.Event
    ) -> Dict[str, Any]:
        """Execute a single case with async reflection after completion.

        Optimized Flow (Async Reflection):
        1. Execute case
        2. Capture snapshot (fast, ~100-200ms)
        3. Release session immediately
        4. Start async reflection task (doesn't block session)

        Args:
            case: Test case dict
            url: Target URL
            cookies: Optional cookies
            dynamic_step_generation: Optional dynamic step config
            language: UI language
            reflector: CaseReflector instance
            finish_event: Event to check for FINISH signal

        Returns:
            Dict with execution results
        """
        case_name = case.get('name', 'Unnamed Case')

        # Check FINISH signal before starting
        if finish_event.is_set():
            logging.info(f"[WithReflection] Skipping case '{case_name}' due to FINISH signal")
            return {
                'case_result': {
                    'case_name': case_name,
                    'status': 'skipped',
                    'final_summary': 'Skipped due to FINISH signal',
                    'failure_type': None
                },
                'recorded_case': None,
                'modified_case': None,
                'skipped': True
            }

        session = None
        result = None
        snapshot = None

        try:
            # Queue.get() blocks when empty - this IS the concurrency control
            # Use None timeout to wait indefinitely - Queue naturally limits concurrency
            session = await self.session_pool.acquire(timeout=None)

            # Move from waiting to execution (after acquiring session)
            if case in self.waiting_list:
                self.waiting_list.remove(case)
            self.execution_list.append(case)

            logging.info(
                f"[WithReflection] Starting case: {case_name} "
                f"(Waiting: {len(self.waiting_list)}, Executing: {len(self.execution_list)}, "
                f"Completed: {len(self.completed_list)})"
            )
            logging.debug(f"[WithReflection] Acquired session {session.session_id} for case: {case_name}")

            # Execute case
            result = await execute_single_case_standalone(
                case=case,
                session=session,
                llm_config=self.llm_config,
                url=url,
                cookies=cookies,
                dynamic_step_generation=dynamic_step_generation,
                language=language
            )

            # Update statistics
            case_result = result.get('case_result', {})
            status = case_result.get('status', 'unknown').lower()

            if status == 'passed':
                self.stats['passed'] += 1
            elif status == 'failed':
                self.stats['failed'] += 1
            elif status == 'warning':
                self.stats['warning'] += 1

            logging.info(f"[WithReflection] Completed case: {case_name} (status: {status})")

            # Incremental save
            await self._save_case_result_incrementally(
                case_result,
                case_name,
                case_index=case.get('_original_index'),
                recorded_case=result.get('recorded_case')
            )

            # Capture snapshot BEFORE releasing session (fast, ~100-200ms)
            if not finish_event.is_set():
                snapshot = await reflector.capture_snapshot(
                    case_result=case_result,
                    session=session,
                    completed_cases=[r.get('case_result', {}) for r in self.completed_list if r],
                    remaining_cases=self.waiting_list
                )

            return result

        except asyncio.CancelledError:
            logging.warning(f"[WithReflection] Case '{case_name}' was cancelled")
            if result is None:
                result = {
                    'case_result': {
                        'case_name': case_name,
                        'status': 'cancelled',
                        'final_summary': 'Case execution was interrupted',
                        'failure_type': 'interrupted'
                    },
                    'recorded_case': None,
                    'modified_case': None,
                    'error': 'Test was cancelled'
                }
            self.stats['failed'] += 1
            await self._save_case_result_incrementally(
                result.get('case_result', {}),
                case_name,
                case_index=case.get('_original_index'),
                recorded_case=result.get('recorded_case')
            )
            raise

        except Exception as e:
            logging.error(f"[WithReflection] Error executing case '{case_name}': {e}", exc_info=True)
            if result is None:
                result = {
                    'case_result': {
                        'case_name': case_name,
                        'status': 'failed',
                        'final_summary': f'Execution error: {str(e)}',
                        'failure_type': 'critical'
                    },
                    'recorded_case': None,
                    'modified_case': None,
                    'error': str(e)
                }
            self.stats['failed'] += 1
            await self._save_case_result_incrementally(
                result.get('case_result', {}),
                case_name,
                case_index=case.get('_original_index'),
                recorded_case=result.get('recorded_case')
            )
            return result

        finally:
            if session:
                await self.session_pool.release(session)
                logging.debug(f"[WithReflection] Released session {session.session_id}")
            if case in self.execution_list:
                self.execution_list.remove(case)
            if result is not None:
                self.completed_list.append(result)
            # Start async reflection AFTER session released (tracked for completion)
            if snapshot:
                reflection_task = asyncio.create_task(
                    reflector.reflect_from_snapshot(snapshot),
                    name=f"reflect_{case_name}"
                )
                self._reflection_tasks.append(reflection_task)

    async def _new_case_consumer(
        self,
        new_cases_queue: asyncio.Queue,
        finish_event: asyncio.Event,
        url: str,
        cookies: Optional[list],
        dynamic_step_generation: Optional[Dict],
        language: str,
        reflector: CaseReflector,
        dynamic_case_counter_start: int
    ):
        """Consume new cases from reflection REPLAN decisions.

        Runs as a background task, processes cases added by reflectors.
        No lock needed - Queue is thread-safe.

        Args:
            new_cases_queue: Queue of new cases from REPLAN
            finish_event: Event to signal stop
            url: Target URL
            cookies: Optional cookies
            dynamic_step_generation: Dynamic step config
            language: UI language
            reflector: CaseReflector instance
            dynamic_case_counter_start: Starting index for dynamic cases
        """
        dynamic_counter = dynamic_case_counter_start
        pending_tasks = []

        logging.info("[NewCaseConsumer] Started, waiting for new cases...")

        while not finish_event.is_set():
            try:
                # Wait for new case with timeout
                case = await asyncio.wait_for(
                    new_cases_queue.get(),
                    timeout=1.0
                )

                # Assign index to dynamic case
                dynamic_counter += 1
                case['_original_index'] = dynamic_counter
                case['_is_dynamic'] = True

                logging.info(f"[NewCaseConsumer] Processing new case: {case.get('name', 'Unnamed')}")

                # Update stats
                self.stats['total_cases'] += 1

                # Add to waiting list
                self.waiting_list.append(case)

                # Create execution task
                task = asyncio.create_task(
                    self._execute_case_with_reflection(
                        case=case,
                        url=url,
                        cookies=cookies,
                        dynamic_step_generation=dynamic_step_generation,
                        language=language,
                        reflector=reflector,
                        finish_event=finish_event
                    )
                )
                pending_tasks.append(task)
                self._tasks.append(task)

            except asyncio.TimeoutError:
                # No new cases, continue waiting
                continue
            except asyncio.CancelledError:
                logging.info("[NewCaseConsumer] Cancelled")
                break
            except Exception as e:
                logging.error(f"[NewCaseConsumer] Error: {e}", exc_info=True)

        # Wait for pending tasks to complete
        if pending_tasks:
            logging.info(f"[NewCaseConsumer] Waiting for {len(pending_tasks)} pending tasks...")
            await asyncio.gather(*pending_tasks, return_exceptions=True)

        logging.info("[NewCaseConsumer] Stopped")

    def _empty_results_with_reflection(self) -> Dict[str, Any]:
        """Return empty results structure with reflection stats."""
        return {
            'case_results': [],
            'recorded_cases': [],
            'modified_cases': [],
            'stats': dict(self.stats),
            'completed_list': [],
            'reflection_stats': {
                'total_reflections': 0,
                'replan_count': 0,
                'continue_count': 0,
                'finish_count': 0,
                'new_cases_generated': 0,
                'errors': 0
            }
        }

    def _aggregate_results_with_reflection(self, reflection_stats: Dict) -> Dict[str, Any]:
        """Aggregate results including reflection statistics.

        Args:
            reflection_stats: Stats from CaseReflector

        Returns:
            Dict with aggregated results and reflection stats
        """
        base_results = self._aggregate_results()
        base_results['reflection_stats'] = reflection_stats
        return base_results
