apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    csi.alibabacloud.com/nas-id: 35bd448d7f
  name: webqa-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeAttributes:
      path: /webqa_data
      server: 35bd448d7f-ibs92.cn-shanghai.nas.aliyuncs.com
    volumeHandle: webqa-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webqa-pvc
  namespace: cloud-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  volumeName: webqa-pv
