# Build stage
FROM eng-center-registry-vpc.cn-shanghai.cr.aliyuncs.com/qa/node:20-alpine as build

WORKDIR /app

COPY frontend/package.json ./
RUN npm install

COPY frontend/ .

ARG VITE_CASE_PORTAL_URL
RUN VITE_CASE_PORTAL_URL=$VITE_CASE_PORTAL_URL npm run build

# Production stage
FROM eng-center-registry-vpc.cn-shanghai.cr.aliyuncs.com/qa/nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
