version: "3.10"

services:
  app:
    image: mmmay0722/webqa-agent:latest
    container_name: webqa-agent
    volumes:
      # Mount configuration file
      - ./config:/app/config:ro
      # Mount logs directory
      - ./logs:/app/logs
      # Mount test results directory
      - ./reports:/app/reports
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Use environment variable with priority
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true  # Identify Docker environment, force headless mode
    restart: "no"    # Development mode no auto-restart for easier debugging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
