icon = {
    "star": "✨",
    "good": "👍",
    "bad": "👎",
    "warning": "⚠️",
    "info": "❗️",
    "question": "❓",
    "ban": "🚫",
    "arrow": "➜",
    "right": "➡️",
    "left": "⬅️",
    "up": "⬆️",
    "down": "⬇️",
    "check": "✅",
    "cross": "❌",
}
