apiVersion: v1
kind: Secret
metadata:
  name: webqa-secrets
  namespace: cloud-staging
type: Opaque
data:
  # Database User: webqa
  DB_USER: d2VicWE=
  DB_PASSWORD: VXVHaXRhaXBxczUtV1gm

  REDIS_PASSWORD: R29vZGxhYjI4

  # LLM API Key (base64 编码)
  # 原始值: sk-nn0loT6nEp9zTcPAXILK9YnRRChG9ecdmM54W2SwMbbFdvN1
  LLM_API_KEY: c2stbm4wbG9UNm5FcDl6VGNQQVhJTEs5WW5SUkNoRzllY2RtTTU0VzJTd01iYkZkdk4x
